### ISSUE TITLE
fix empty harbor username/password

### ISSUE THREAD

**Issue by semik** [3KeyCompany/CZERTAINLY-Appliance-Tools#40]
TUI saves empty passwords into `docker.yaml`  like this:
```
---
docker:
  server: harbor.3key.company
  email: 
  secret: regcred
  username: 
  password: 
```

Later this is parsed into Ansible variable:
```
TASK [czertainly : debug] ******************************************************
ok: [localhost] => {
    "docker": {
        "email": null,
        "password": null,
        "secret": "regcred",
        "server": "harbor.3key.company",
        "username": null
    }
}
```

null is in Ansible defined so following test:
```
  - name: verify harbor credentials
    ansible.builtin.uri:
      url: 'https://harbor.3key.company/api/v2.0/users/current'
      user: "{{ docker.username }}"
      password: "{{ docker.password }}"
      method: GET
      force_basic_auth: true
      headers:
        accept: application/json
    when: (docker.username is defined) and (docker.password is defined)
```
evaluates as true. 

`null` value evaluates as empty string `""` or as string `None` depending on usage.

```
  - name: "show docker.username as a string #1"
    debug: msg={{ docker.username }}

  - name: "show docker.username as a string #2"
    debug: msg={{ docker.username | string }}
```

```

TASK [czertainly : show docker.username as a string #1] ************************
ok: [localhost] => {
    "msg": ""
}

TASK [czertainly : show docker.username as a string #2] ************************
ok: [localhost] => {
    "msg": "None"
}
```

# 😭😭😭

Solution should be not to save empty values into var files, like I'm doing for other var.
